### PR TITLE
proposal / tree folders structure

### PR DESCRIPTION
**Pull request by kcynia85**
what do you think?

### CODE REVIEW

**Comment by JaniecMichal** [comment]
I think is okay but we should remember that Redux can be useful on next stage of development.  All business logic about connection with API and view generating should be connected with app state which will be management by Redux. :)

**Comment by kamila-duda** [comment]
We will be using both store.js and redux in our application, so there is no point in deleting it, we can change these files later.

**Comment by kamila-duda** [comment]
Other changes are ok of course :)

**Comment by kcynia85** [comment]
Thanks for your feedback guys. ☺️ I agree with you in all. Kamila could you merge this request? ☺️

**Comment by kamila-duda** [comment]
Done :)

**Pull request merged**
