### PR TITLE
Connection error page

### PR DESCRIPTION
**Pull request by JaniecMichal**
I created Connection error  page. Please check if everything is okay and confirm that I can merge this branch.

### CODE REVIEW

**Comment by JaniecMichal** [comment]
I noticed that mobile view should looks a little bit different that I made. I will try to change them asap.

**Comment by kamila-duda** [comment]
Hi, I checked ErrorPage and it looks great! I found error in my theme.js, becouse i miss "#" in blue color, so is the reason why button was white. I correted it in my code. Font inside button looks correct, but I have no idea, why they looks different in Figma. It's a small thing, but maybe you'll limit the width of the ErrorMessage, then maybe the text will wrapped to the second line?

**Comment by JaniecMichal** [comment]
Please confirm if I can merge or I should correct this component. Do you think that discrepancy is irrelevant and we can proceed?

**Comment by JaniecMichal** [comment]
Please confirm if I can merge or I should correct this component. Do you think that discrepancy is irrelevant and we can proceed?

**Pull request merged**
