### PR TITLE
Container

### PR DESCRIPTION
**Pull request by kamila-duda**
It is simple component, I was based on Container Component from To-do list. I don't know how big top-margin to set, becouse Navigation component change height when page resize.

### CODE REVIEW

**Comment by JaniecMichal** [comment]
Styles for this component We should check again because when I check it in App.js and try to render <NavBar> and <Container> then is problem because NavBar come over Container and then all content is  covered up by Navigation. Probably the problem is also in styles for NavBar. We mentioned in previous Pull Request that _position_ selector should have other value maybe fixed :)

**Comment by kamila-duda** [comment]
I checked the hight of navigation when page resize. Up to the device width 768, the navigation is 80 pixels high, and from 767 130 pixels high. I try to set  a breakpoint  in the container component and add the top padding to it, so that the navigation does not cover anything. Ok?

**Comment by kamila-duda** [comment]
I added padding. Please look at this change to see if it's okay now.

**Comment by kamila-duda** [comment]
May I merge this pull request?

**Comment by JaniecMichal** [comment]
I confirm. Please merge!

**Pull request merged**
