### PR TITLE
Hero banner

### PR DESCRIPTION
**Pull request by JaniecMichal**
Hero Banner is ready to use. We can think about correcting one thing on the next stage. In Figma project used interested effect for image but I don't have idea how make these same effect in css I had try with blur, opacity but I can't achive similar effect. Have you any idea how We can achive this effect?

Please give me information if everything with HeroBanner is okay. I am waiting for your confirmation.

### CODE REVIEW

**Comment by kamila-duda** [comment]
You did a good job :) About shadow around image, I propose you to do ::after pseudo element for Container, and add style for desktop: `content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    -webkit-box-shadow: inset 0px 0px 54px 74px rgba(0,0,0,1);
-moz-box-shadow: inset 0px 0px 54px 74px rgba(0,0,0,1);
box-shadow: inset 0px 0px 54px 74px rgba(0,0,0,1);` 
and for mobile:
`-webkit-box-shadow: inset 0px 0px 30px 28px rgba(0,0,0,1);
-moz-box-shadow: inset 0px 0px 30px 28px rgba(0,0,0,1);
box-shadow: inset 0px 0px 30px 28px rgba(0,0,0,1);`
In my computer I see a little space between navbar and banner. Maybe you add margin-top: 60px (and 105px for small) to MovieBanner? And some padding-bottom? And don't forget change background color to simple black in MovieBanner).

**Comment by JaniecMichal** [comment]
Thank you Kamila for help. I corrected Components according to your instruction and now looks perfect! Please check again and confirm if I can merge or you can do it  👍

**Comment by JaniecMichal** [comment]
Now, should be ok. Please check again. :)

**Comment by kamila-duda** [comment]
Yes, it's ok. I merge it!

**Pull request merged**
