### PR TITLE
Styled Navigation component with Search - without logic

### PR DESCRIPTION
**Pull request by kamila-duda**
Responsive Navigation component with Search input - without logic. I added breakpoints from theme.js

### CODE REVIEW

**Comment by kamila-duda** [comment]
I set position absolute, but it's wrong. It should be fixed or relative. What do you think?

**Comment by JaniecMichal** [comment]
In video about Figma Krzysztof talked that we won't use all selectors in our project. I think that selector _position_ and also _left_, _right_ and _top_ are not neccesary because Navbar as first element always is on the top.

**Comment by kamila-duda** [comment]
Yes,  but if we want see always navbar on the top of page, we must stick it on top (position fixed in this case). What you think, in this project navbar is always visible when page is scroll or not? Or maybe we should decided about it themselves?

**Review by JaniecMichal — APPROVED** [review]
@kamila-duda  thank you for clarification. Now I understand your view point. I agree that better will be when NavBar is fixed. Sticky NavBar is very good idea!👍

**Comment by JaniecMichal** [comment]
After double check, fixed value can't be. Maybe sticky? ) We must check Components arrangement with NavBar and Container ;)

**Review by JaniecMichal — APPROVED** [review]
Now should be great! :)

**Pull request merged**
