### PR TITLE
created template tile plus tile container

### PR DESCRIPTION
**Pull request by kcynia85**

### CODE REVIEW

**Comment by kamila-duda** [comment]
Very nice component. I would just add a title field in StyledTileSContainer and use inside "{props.children}" instead of list of Tiles. What you think about it?

**Comment by kamila-duda** [comment]
Update yours Container component, becouse you have old version, and that's why this branch has conflicts.

**Comment by kcynia85** [comment]
Oh, my dear Kamila and Michał could you lookup for my changes? :) Thanks in advance.

**Comment by kcynia85** [comment]
> Very nice component. I would just add a title field in StyledTileSContainer and use inside "{props.children}" instead of list of Tiles. What do you think about it?

I'm really really sorry that I didn't notice that question earlier. We'll see about how will we able to handle a logic part and TMDb API fetching.

**Pull request merged**
